<?php

declare(strict_types=1);

namespace SymPress\Cli\Tests\Generator;

use PHPUnit\Framework\TestCase;
use SymPress\Cli\Catalog\DefaultProfileCatalog;
use SymPress\Cli\Catalog\DefaultTemplateCatalog;
use SymPress\Cli\Generator\ProjectGenerator;
use SymPress\Cli\Model\PackageReference;
use SymPress\Cli\Model\ProjectConfiguration;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

final class ProjectGeneratorTest extends TestCase
{
    /** @var list<string> */
    private array $temporaryDirectories = [];

    protected function tearDown(): void
    {
        (new Filesystem())->remove($this->temporaryDirectories);
    }

    public function testRemovesCopiedLockWhenRequirementsChangeWithoutSetup(): void
    {
        $projectDir = $this->temporaryProjectPath();
        $runner = new FixtureProjectCommandRunner($this->starterComposer());
        $configuration = $this->configuration(
            $projectDir,
            packages: [new PackageReference('sympress/assets')],
        );

        self::assertSame(0, (new ProjectGenerator($runner))->generate($configuration, $this->style()));
        self::assertFileDoesNotExist($projectDir . '/composer.lock');
    }

    public function testRemovesCopiedLockBeforeSetupRuns(): void
    {
        $projectDir = $this->temporaryProjectPath();
        $runner = new FixtureProjectCommandRunner($this->starterComposer());
        $configuration = $this->configuration(
            $projectDir,
            packages: [new PackageReference('sympress/assets')],
            runSetup: true,
        );

        self::assertSame(0, (new ProjectGenerator($runner))->generate($configuration, $this->style()));
        self::assertFalse($runner->lockPresentDuringSetup);
    }

    public function testPreservesCopiedLockWhenComposerJsonIsUnchanged(): void
    {
        $projectDir = $this->temporaryProjectPath();
        $runner = new FixtureProjectCommandRunner($this->starterComposer());
        $configuration = $this->configuration($projectDir);

        self::assertSame(0, (new ProjectGenerator($runner))->generate($configuration, $this->style()));
        self::assertFileExists($projectDir . '/composer.lock');
    }

    /** @return array<string, mixed> */
    private function starterComposer(): array
    {
        return [
            'name'        => 'acme/customer-portal',
            'description' => 'Customer Portal project generated by SymPress CLI.',
            'require'     => ['php' => '^8.5'],
        ];
    }

    /**
     * @param list<PackageReference> $packages
     */
    private function configuration(
        string $projectDir,
        array $packages = [],
        bool $runSetup = false,
    ): ProjectConfiguration {
        return new ProjectConfiguration(
            template: (new DefaultTemplateCatalog())->first(),
            profile: (new DefaultProfileCatalog())->default(),
            directory: $projectDir,
            projectName: 'Customer Portal',
            projectSlug: 'customer-portal',
            composerPackageName: 'acme/customer-portal',
            ddevTld: 'ddev.site',
            wpAdminUsername: 'admin',
            wpAdminPassword: 'secret-secret',
            packages: $packages,
            runSetup: $runSetup,
        );
    }

    private function temporaryProjectPath(): string
    {
        $directory = sys_get_temp_dir() . '/sympress-cli-' . bin2hex(random_bytes(6));
        self::assertTrue(mkdir($directory, 0777, true));
        $this->temporaryDirectories[] = $directory;

        return $directory . '/project';
    }

    private function style(): SymfonyStyle
    {
        return new SymfonyStyle(new ArrayInput([]), new BufferedOutput());
    }
}
