<?php

declare(strict_types=1);

namespace SymPress\Cli\Generator;

use JsonException;
use RuntimeException;
use SymPress\Cli\Model\PackageReference;
use SymPress\Cli\Model\ProjectConfiguration;

final class ComposerJsonEditor
{
    public function apply(string $projectDir, ProjectConfiguration $configuration): bool
    {
        $path = $projectDir . '/composer.json';

        if (!is_file($path)) {
            throw new RuntimeException(sprintf('composer.json was not found in "%s".', $projectDir));
        }

        $data = $this->read($path);
        $original = $data;
        $data['name'] = $configuration->composerPackageName;
        $data['description'] = sprintf('%s project generated by SymPress CLI.', $configuration->projectName);

        $this->mergePackages($data, 'require', $configuration->packages);
        $this->mergePackages($data, 'require-dev', $configuration->devPackages);
        $this->mergeRepositories($data, [...$configuration->packages, ...$configuration->devPackages]);

        if ($data === $original) {
            return false;
        }

        $encoded = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        file_put_contents($path, $encoded . "\n");

        return true;
    }

    /**
     * @param list<PackageReference> $packages
     * @param list<PackageReference> $devPackages
     *
     * @return list<string>
     */
    public function mergePackageReferences(string $projectDir, array $packages, array $devPackages): array
    {
        $path = $projectDir . '/composer.json';

        if (!is_file($path)) {
            throw new RuntimeException(sprintf('composer.json was not found in "%s".', $projectDir));
        }

        $data = $this->read($path);
        $changed = [
            ...$this->mergeMissingPackages($data, 'require', $packages),
            ...$this->mergeMissingPackages($data, 'require-dev', $devPackages),
        ];
        $this->mergeRepositories($data, [...$packages, ...$devPackages]);

        $encoded = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        file_put_contents($path, $encoded . "\n");

        return $changed;
    }

    /**
     * @param list<PackageReference> $packages
     * @param list<PackageReference> $devPackages
     *
     * @return list<string>
     */
    public function missingPackageReferences(string $projectDir, array $packages, array $devPackages): array
    {
        $path = $projectDir . '/composer.json';

        if (!is_file($path)) {
            throw new RuntimeException(sprintf('composer.json was not found in "%s".', $projectDir));
        }

        $data = $this->read($path);

        return [
            ...$this->missingPackages($data, 'require', $packages),
            ...$this->missingPackages($data, 'require-dev', $devPackages),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function read(string $path): array
    {
        try {
            $data = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new RuntimeException(
                sprintf('Unable to parse "%s": %s', $path, $exception->getMessage()),
                0,
                $exception,
            );
        }

        if (!is_array($data)) {
            throw new RuntimeException(sprintf('Expected "%s" to contain a JSON object.', $path));
        }

        return $data;
    }

    /**
     * @param array<string, mixed> $data
     * @param list<PackageReference> $packages
     */
    private function mergePackages(array &$data, string $section, array $packages): void
    {
        if ($packages === []) {
            return;
        }

        if (!isset($data[$section]) || !is_array($data[$section])) {
            $data[$section] = [];
        }

        foreach ($packages as $package) {
            if ($package->suggested && isset($data[$section][$package->name])) {
                continue;
            }

            $data[$section][$package->name] = $package->constraint;
        }

        ksort($data[$section]);
    }

    /**
     * @param array<string, mixed> $data
     * @param list<PackageReference> $packages
     *
     * @return list<string>
     */
    private function mergeMissingPackages(array &$data, string $section, array $packages): array
    {
        if ($packages === []) {
            return [];
        }

        if (!isset($data[$section]) || !is_array($data[$section])) {
            $data[$section] = [];
        }

        $changed = [];

        foreach ($packages as $package) {
            if (isset($data[$section][$package->name])) {
                continue;
            }

            $data[$section][$package->name] = $package->constraint;
            $changed[] = $package->name;
        }

        ksort($data[$section]);

        return $changed;
    }

    /**
     * @param array<string, mixed> $data
     * @param list<PackageReference> $packages
     *
     * @return list<string>
     */
    private function missingPackages(array $data, string $section, array $packages): array
    {
        $sectionData = isset($data[$section]) && is_array($data[$section]) ? $data[$section] : [];
        $missing = [];

        foreach ($packages as $package) {
            if (isset($sectionData[$package->name])) {
                continue;
            }

            $missing[] = $package->name;
        }

        return $missing;
    }

    /**
     * @param array<string, mixed> $data
     * @param list<PackageReference> $packages
     */
    private function mergeRepositories(array &$data, array $packages): void
    {
        $urls = [];

        foreach ($packages as $package) {
            if ($package->repositoryUrl !== null) {
                $urls[$package->repositoryUrl] = true;
            }
        }

        if ($urls === []) {
            return;
        }

        if (!isset($data['repositories']) || !is_array($data['repositories'])) {
            $data['repositories'] = [];
        }

        $knownUrls = [];

        foreach ($data['repositories'] as $repository) {
            if (is_array($repository) && isset($repository['url']) && is_string($repository['url'])) {
                $knownUrls[$repository['url']] = true;
            }
        }

        foreach (array_keys($urls) as $url) {
            if (isset($knownUrls[$url])) {
                continue;
            }

            $data['repositories'][] = [
                'type' => 'vcs',
                'url' => $url,
            ];
        }
    }
}
